<?php

/**
 * @file
 * Defines the WmSingles module.
 *
 * @category module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;

/**
 * Implements hook_entity_operation_alter().
 *
 * @param array $operations
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function wmsingles_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity)
{
    /** @var AccountInterface $user */
    $user = \Drupal::currentUser();
    /** @var EntityInterface|null $single */
    $single = \Drupal::service('wmsingles')->getSingleByBundle($entity->bundle());

    if (
        $entity->getEntityTypeId() !== 'node'
        || !$single
    ) {
        return;
    }

    if (
        !$user->hasPermission('administer wmsingles')
        && !empty($operations['delete'])
    ) {
        unset($operations['delete']);
    }

    $operations['view'] = [
        'title' => 'View',
        'weight' => 20,
        'url' => Url::fromRoute('entity.node.canonical', ['node' => $entity->id()]),
    ];

    if ($user->hasPermission('administer content types')) {
        $operations['edit_type'] = [
            'title' => 'Edit type',
            'weight' => 19,
            'url' => Url::fromRoute('entity.node_type.edit_form', ['node_type' => $single->bundle()]),
        ];
    }
}
