<?php

/**
 * @file
 * Defines the WmSingles module.
 *
 * @category module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_entity_operation_alter().
 *
 * @param array $operations
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function wmsingles_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity)
{
    /** @var AccountInterface $user */
    $user = \Drupal::currentUser();
    /** @var EntityInterface|null $single */
    $single = \Drupal::service('wmsingles')->getSingleByBundle($entity->bundle());

    if ($entity->getEntityTypeId() !== 'node' || !$single) {
        return;
    }

    $operations['view'] = [
        'title' => t('View'),
        'weight' => 5,
        'url' => Url::fromRoute('entity.node.canonical', ['node' => $entity->id()]),
    ];

    $operations['edit']['weight'] = 10;

    if (!$user->hasPermission('administer wmsingles') && !empty($operations['delete'])) {
        unset($operations['delete']);
    } else {
        $operations['delete']['weight'] = 15;
    }

    $nodeType = NodeType::load($entity->bundle());
    $nodeTypeOperations = \Drupal::entityTypeManager()
        ->getListBuilder('node_type')
        ->getOperations($nodeType);

    if (isset($nodeTypeOperations['edit'])) {
        $nodeTypeOperations['edit']['title'] = t('Edit type');
        $nodeTypeOperations['edit-type'] = $nodeTypeOperations['edit'];
        unset($nodeTypeOperations['edit']);
    }

    $operations += $nodeTypeOperations;
}
